feature/update addresses controller
coupin/coupin-api pull request #107
Opened 2021-09-23 17:08 UTC by bolorundurowb

2021-09-24 14:58 UTC, Saint-lawal requested changes

2021-09-24 14:58 UTC, Saint-lawal commented on customer/controllers/AddressesCtrl.js
> +      owner: user.id
This was a mistake on my part. This should be { $and: [{ owner: user.id }, { _id: req.param.id }] }. Please help confirm using the routes.

2021-09-24 23:27 UTC, bolorundurowb commented on customer/controllers/AddressesCtrl.js
> +      owner: user.id
Done

2021-09-26 16:54 UTC, Saint-lawal approved these changes

2021-09-26 16:54 UTC, merged