Merchant bank accounts
coupin/coupin-api pull request #84
Opened 2021-08-29 19:49 UTC by adetola-ralph

2021-09-06 11:25 UTC, Saint-lawal requested changes
LGTM just a few changes

2021-09-06 11:25 UTC, Saint-lawal commented on customer/routes/accounts.js
> +      .route('./accounts/confirm')
We should remove the "." in the route

2021-09-06 11:25 UTC, Saint-lawal commented on shared/models/User.js
> +        match: [/^\d{3}$/, 'Please enter a valid bank code'],
Not all bank codes are 3 digits apparently. Saw one that's 5 digits.
![Screenshot 2021-09-06 at 12 24 54](https://user-images.githubusercontent.com/22102054/132210309-bd215170-05f3-4346-964d-5b451e58b7bc.png)

2021-09-06 13:15 UTC, bolorundurowb commented on customer/controllers/accounts.js
> +module.exports = {
Can we write this one in the new `class` style?

2021-09-06 13:15 UTC, bolorundurowb commented on customer/controllers/merchant.js
> +                Raven.captureException(error);
The logger reports to raven on error

2021-09-13 10:05 UTC, Saint-lawal requested changes

2021-09-13 10:05 UTC, Saint-lawal commented on customer/controllers/accounts.js
> +  confirmAccountDetails(req, res) {
We need to make these static or else it would throw an error.

2021-09-13 10:05 UTC, Saint-lawal commented on customer/controllers/accounts.js
> +  getBank(req, res) {
Same with this.

2021-09-13 11:28 UTC, adetola-ralph commented on customer/controllers/accounts.js
> +  confirmAccountDetails(req, res) {
not really, I am instantiating the class before exporting it

2021-09-13 11:28 UTC, adetola-ralph commented on customer/controllers/accounts.js
> +module.exports = new Accounts();
this is where I am instantiating

2021-09-13 11:29 UTC, merged